projects:
  - label: one
    path: C:\buildkite-agent\builds\DESKTOP-00VTEVI-1\starfall-projects\github-test\one
  - label: two
    path: C:\buildkite-agent\builds\DESKTOP-00VTEVI-1\starfall-projects\github-test\two


steps:
  - label: ":hammer: Example Script"
    command: 
      - cd $$BUILDPIPE_PROJECT_PATH
      - script.bat
    notify:
      - github_commit_status:
          context: "$$BUILDPIPE_PROJECT_PATH"
