projects:
  - label: one
    path: one
  - label: two
    path: two


steps:
  - label: ":hammer: Example Script"
    command: 
      - cd $$BUILDPIPE_PROJECT_PATH
      - script.bat
    notify:
      - github_commit_status:
          context: " $$BUILDPIPE_PROJECT_PATH"
