steps:
  - label: "Run script"
    command: "script.sh"
    agents:
      os: "wsl"
    notify:
      - github_commit_status:
          context: "custom-stat"
  - label: "Another script with no comment"
    command: "echo 'yo'"
