steps:
  - label: "First script"
    command: "script.sh"
    agents:
      os: "wsl"
    notify:
      - github_commit_status:
          context: "custom-status"
  - label: "Second script"
    command: "echo 'hello from a step with no notification'"
notify:
  github_check
